### ISSUE TITLE
Random errors from CORS proxy

### ISSUE THREAD

**Issue by carbolymer** [Ibit-to/google-unlocked#10]
Current CORS proxy https://secret-ocean-49799.herokuapp.com returns errors randomly. You can see on the screens that some requests result in HTTP 503 error. A more reliable proxy solution should be used.

![Screenshot_2019-04-10_22-12-53](https://user-images.githubusercontent.com/228866/55910174-0c600f00-5bde-11e9-9196-d04b2345badf.png)
![Screenshot_2019-04-10_22-13-13](https://user-images.githubusercontent.com/228866/55910175-0c600f00-5bde-11e9-83b0-10a5f9a2069e.png)

**Comment by Ibit-to** [comment]
Switched back to cors anywhere domain but that might be slow...

**Comment by Ibit-to** [comment]
https://gist.github.com/jimmywarting/ac1be6ea0297c16c477e17f8fbe51347 for ref
