### ISSUE TITLE
What now?

### ISSUE THREAD

**Issue by marcussacana** [Ibit-to/google-unlocked#12]
The lumendatabase now hide all links, there are any alternative service?

**Comment by Ibit-to** [comment]
There are 2 options: 1) use the domain that's shown instead of the full link or 2) just use https://ibit.uno/popular/ :)

**Comment by marcussacana** [comment]
Well, I don't use to download torrents anyway, the domain huh...
better than nothing....

**Comment by marcussacana** [comment]
what about create a integration api to the guerrillamail.com service that don't have bot protection
and show the lumen view request captcha to the user complete it, then automatically catch the email with the access link and get the links...?
It's a lot of work but will be more 'fast' than do manually.

**Comment by Ibit-to** [comment]
We will try to dedicate time to include domains instead of full URL. Meanwhile we welcome pull requests.

**Comment by marcussacana** [comment]
I'm not good with js, but maybe...
