### ISSUE TITLE
Missing Firefox version

### ISSUE THREAD

**Issue by haarp** [Ibit-to/google-unlocked#13]
Hey,

the Firefox install instructions, since it got censored from AMO, mention manually installing it. Manually installing what? There's no compatible addon file to be found anywhere. How do I install it?

Thanks!

**Comment by Ibit-to** [comment]
I think you can just use the crx file from the release page https://github.com/Ibit-to/google-unlocked/releases

**Comment by haarp** [comment]
Unfortunately, no. Firefox deems the file to be "corrupt", which probably means it cannot use it.

**Comment by Ibit-to** [comment]
You're right. Here is the link https://github.com/Ibit-to/google-unlocked/releases/download/v1.5/google_unlocked-1.5.xpi

Thanks for pointing it out!

**Comment by haarp** [comment]
Looks like it installed fine. Thanks!
