### ISSUE TITLE
Unable to install the extension.

### ISSUE THREAD

**Issue by Mooht** [Ibit-to/google-unlocked#17]
![image](https://user-images.githubusercontent.com/55190524/64693945-156b4a00-d4b6-11e9-94df-00d11187dd9e.png)

The required file is missing. I don't know where I am going wrong, Any help is appreciated.

**Comment by RanHum** [comment]
You've downloaded source code, go [to releases' page](https://github.com/Ibit-to/google-unlocked/releases) and install `google-unlocked.crx`
