### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by hybla0** [Ibit-to/google-unlocked#19]
Hi,
i am using Google Chrome v79.0.3945.88 with your extension v1.5 but at the bottom of the page search for "ibit.to" i don't see any results, only : "In response to multiple complaints that we received under the US Digital Millennium Copyright Act, we have removed 4 results from this page. If you wish, you may read the DMCA complaints that caused the removals at LumenDatabase.org: Complaint, Complaint"

**Comment by Ibit-to** [comment]
Can you provide the search URL?

**Comment by hybla0** [comment]
@Ibit-to [URL](https://www.google.com/search?hl=en&q=site%3Aibit.to&oq=site%3Aibit.to) i don't know why, but now it works, it displays only links to homepages of the websites tho...

**Comment by Ibit-to** [comment]
Usually it takes few seconds but could take longer depending on your internet conn.
