### ISSUE TITLE
Firefox version

### ISSUE THREAD

**Issue by darkhog** [Ibit-to/google-unlocked#2]
Please add a Firefox version of the extension.

**Comment by Ibit-to** [comment]
I just submitted it to Firefox add-ons website. I hope they accept it. Meanwhile, you can install it manually by enabling the temporary add-ons and loading the zip file from the release page. Let me know how it goes..

**Comment by optomux** [comment]
Sweeeeeeeet!

**Comment by Ibit-to** [comment]
Published! https://addons.mozilla.org/en-US/firefox/addon/google-unlocked/
