### ISSUE TITLE
No longer works.

### ISSUE THREAD

**Issue by AR45H** [Ibit-to/google-unlocked#21]

**Comment by DineshSolanki** [comment]
Just checked, still working.

**Comment by AR45H** [comment]
Perhaps I should have clarified a bit. On firefox it has reverted back to the default message of google having removed some results due to DMCA.

**Comment by AR45H** [comment]
Nevermind, it's the same on chrome as well. I just checked.

**Comment by DineshSolanki** [comment]
wait for 2-3 seconds, it works here, I'm on firefox. Haven't checked on chrome. 
![image](https://user-images.githubusercontent.com/15937452/92123368-2ffea780-ee1a-11ea-89ff-69c330dffa67.png)

**Comment by AR45H** [comment]
Page has been open for a while and I just refreshed several times waiting anywhere between 5 to 20 sec each time. Nothing.

**Comment by DineshSolanki** [comment]
would you mind giving the search term away or see if you could search "Ibit.to"

**Comment by AR45H** [comment]
But what's important is that I haven't had any success with my normal searches regarding warez and pirate materials.

**Comment by DineshSolanki** [comment]
ok, so I did some different searches, some books, and software and it still works. I don't know if that's the case of yours but sometimes Google puts some image results or other things between the URLs and DMCA message, I know uh seems a silly little thing but you might want to check it.
"The URLs are above the screen of this picture" instead of being at the bottom.
![image](https://user-images.githubusercontent.com/15937452/92127257-c1701880-ee1e-11ea-8623-c287f312ac82.png)

**Comment by Maxxone2008** [comment]
It doesn't work when freshly installed on chrome. I tried the "Ibit.to" search.

**Comment by IRlyLikeBac0n** [comment]
Just dropping by to confirm that I'm getting the same problem. I see the list of unblocked domains at the bottom of the page, but clicking any of them simply leads to the base URL, so it's not helpful. 

Taking this moment to ask, is this project still being maintained? Seems like most progress has dropped off :(

**Comment by Matterhorn56** [comment]
from https://ibit.ws/post/google-unlocked/
![image](https://user-images.githubusercontent.com/12612637/100157808-d0d88e00-2e70-11eb-88e3-981245125f80.png)

**Comment by klesun** [comment]
For me "Ibit.to" search works (extension does add the urls), but for example "моя прекрасная няня торрент скачать" does not work (only the "In response to multiple complaints" message, no urls, waited for 5 minutes, nothing)

**Comment by AetheralMeowstic** [comment]
It doesn't work anymore. Please update it to work with the way Lumen Database has started to work.

**Comment by Ibit-to** [comment]
Open for PRs guys!
