### ISSUE TITLE
cors-anywhere.herokuapp.com isn't working as a proxy

### ISSUE THREAD

**Issue by carbolymer** [Ibit-to/google-unlocked#9]
Simply put, extension does not work. Every request through cors-anywhere.herokuapp.com results in HTTP 404 error: `Not found because of proxy error: Error: connect ECONNREFUSED 128.103.64.94:443`. Details from chromium developer tools in the attachment:

![example_request](https://user-images.githubusercontent.com/228866/55576314-57c37a80-5711-11e9-89ed-7a70963f7990.png)
![example_request2](https://user-images.githubusercontent.com/228866/55576315-57c37a80-5711-11e9-8694-866e75bb2f3f.png)

**Comment by Ibit-to** [comment]
Used to work fine. Any alternatives?
